### ISSUE TITLE
Blank screen when excluding arm64 from simulator sdk

### ISSUE THREAD

**Issue by steelzeh** [ionic-team/ionic-portals-ios#46]
if arm64 is added to Excluded Archives -> Any iOS Simulator SDK, then when trying to show any portal it just shows blank screen.

**Comment by Steven0351** [comment]
Can you provide a minimal reproduction? I'm unable to duplicate. Were you able to get the portal to render before adding arm64 to excluded architectures?

**Comment by steelzeh** [comment]
I think this only happens on M1 when testing on simulator without Rosetta.

1. Create new project
2. Install Portals via Pod
3. Portals works fine
4. Exclude arm64 from Any iOS Simulator SDK
5. Portals not working.

On Discord Minsky mentioned that this was an issue with Capacitor, and has been fixed in 4.1.0. But seems that Portals uses 3.7.0.

**Comment by steelzeh** [comment]
[portals-test.zip](https://github.com/ionic-team/ionic-portals-ios/files/9601322/portals-test.zip)
Here is a test project

**Comment by steelzeh** [comment]
Okay yeah makes sense.

Yes one of the libraries that we use is not working compatible for arm64, and may not be sadly.

**Comment by Steven0351** [comment]
This issue should be resolved now that version 0.7.0 depends on Capacitor 4.4+
