### ISSUE TITLE
iOS: 0.5.0 Swift runtime error

### ISSUE THREAD

**Issue by TobiasHesselinkTopicus** [ionic-team/ionic-portals-ios#9]
Installed the following pod: 'IonicPortals', '~> 0.5.0'
Got 2 runtime errors in XCode:
![Schermafbeelding 2022-04-12 om 10 25 53](https://user-images.githubusercontent.com/80394646/162916293-2ba63722-cc9f-41f4-928d-2a91138e7513.png)
![Schermafbeelding 2022-04-12 om 10 25 39](https://user-images.githubusercontent.com/80394646/162916300-aa1e2d60-73b4-4ad6-8a6f-1a3a11408d21.png)
Help would be appreciated. Thanks in advance.

**More info:**
_Podfile_
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

use_frameworks!
use_modular_headers!

def shared_pods
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'IonicPortals', '~> '0.5.0'
end

target "Core" do
    pod 'RxSwift', '~> 5.1.1'
    pod 'RxCocoa', '~> 5.1.1'
    pod 'RxDataSources', '~> 4.0.1'
    pod 'loady'
    shared_pods
end

target "HIP" do
    pod 'Batch', '~> 1.15'
    shared_pods
end

target "CoreTests" do
    inherit! :search_paths
    pod 'RxBlocking', '~> 5.1.1'
    pod 'RxTest', '~> 5.1.1'
end
```

-----------------
_Xcode Project:_
Deployment target: iOS 13+

**Comment by Steven0351** [comment]
Upgrading to 0.5.1 will fix this
